package mainPack;

public enum FilterOption {
	NONE, HIGH, MID, LOW, SPECIAL_MID, SPECIAL_LOW, GUARD_CRUSH, MOVE_A, MOVE_B, MOVE_K, MOVE_SIMULTANEOUS, MOVE_EIGHTWAYRUN, MOVE_THROW,
	MOVE_EDGE, MOVE_STANCE, HORIZONTAL, VERTICAL, STAB, BODY, TECH_CROUCH, TECH_JUMP, SUPER_TECH_CROUCH, SUPER_TECH_JUMP, FORCE_CROUCH
}
